version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        # npm run start
        npm run dev
      "
